# Generated by Django 4.2.9 on 2024-01-09 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_rename_actors_actor'),
        ('genres', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
